//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 10:25:06 AM CEST 
//


package it.eng.dm.common.mail.segnatura.old;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Destinatario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Destinatario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}Amministrazione"/>
 *             &lt;element ref="{}AOO" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}Denominazione"/>
 *             &lt;element ref="{}Persona" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}Persona" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element ref="{}IndirizzoTelematico" minOccurs="0"/>
 *         &lt;element ref="{}Telefono" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Fax" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}IndirizzoPostale" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Destinatario", propOrder = {
    "content"
})
public class Destinatario {

    @XmlElementRefs({
        @XmlElementRef(name = "Telefono", type = JAXBElement.class),
        @XmlElementRef(name = "Amministrazione", type = JAXBElement.class),
        @XmlElementRef(name = "IndirizzoPostale", type = JAXBElement.class),
        @XmlElementRef(name = "Fax", type = JAXBElement.class),
        @XmlElementRef(name = "IndirizzoTelematico", type = JAXBElement.class),
        @XmlElementRef(name = "Persona", type = JAXBElement.class),
        @XmlElementRef(name = "Denominazione", type = JAXBElement.class),
        @XmlElementRef(name = "AOO", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Persona" is used by two different parts of a schema. See: 
     * line 177 of file:/C:/wk_jac/mailserver/src/main/resources/segnatura_old_vale.xsd
     * line 175 of file:/C:/wk_jac/mailserver/src/main/resources/segnatura_old_vale.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Telefono }{@code >}
     * {@link JAXBElement }{@code <}{@link Amministrazione }{@code >}
     * {@link JAXBElement }{@code <}{@link IndirizzoPostale }{@code >}
     * {@link JAXBElement }{@code <}{@link Fax }{@code >}
     * {@link JAXBElement }{@code <}{@link IndirizzoTelematico }{@code >}
     * {@link JAXBElement }{@code <}{@link Persona }{@code >}
     * {@link JAXBElement }{@code <}{@link AOO }{@code >}
     * {@link JAXBElement }{@code <}{@link Denominazione }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
