//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.07 at 02:48:35 PM CEST 
//


package it.eng.utility.email.util.daticert;

import it.eng.aurigamailbusiness.daticert.Postacert;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.eng.utility.email.util.daticert package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.eng.utility.email.util.daticert
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ricezione }
     * 
     */
    public Ricezione createRicezione() {
        return new Ricezione();
    }

    /**
     * Create an instance of {@link Destinatari }
     * 
     */
    public Destinatari createDestinatari() {
        return new Destinatari();
    }

    /**
     * Create an instance of {@link Postacert }
     * 
     */
    public Postacert createPostacert() {
        return new Postacert();
    }

    /**
     * Create an instance of {@link Dati }
     * 
     */
    public Dati createDati() {
        return new Dati();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Intestazione }
     * 
     */
    public Intestazione createIntestazione() {
        return new Intestazione();
    }

    /**
     * Create an instance of {@link Ricevuta }
     * 
     */
    public Ricevuta createRicevuta() {
        return new Ricevuta();
    }

}
