ALTER TABLE MAILBOX DROP CONSTRAINT MAILBOX_FK
ALTER TABLE MAILBOX_ACCOUNT_CONFIG DROP CONSTRAINT MAILBOX_ACCOUNT_CONFIG_FK;
ALTER TABLE MAILBOX_CONFIG DROP CONSTRAINT MAILBOX_CONFIG_FK;
ALTER TABLE MAILBOX_MESSAGE DROP CONSTRAINT MAILBOX_MESSAGE_FK;
ALTER TABLE MAILBOX_MESSAGE_OPERATION DROP CONSTRAINT MAILBOX_MESSAGE_OPERATION_FK_1;
ALTER TABLE MAILBOX_MESSAGE_OPERATION DROP CONSTRAINT MAILBOX_MESSAGE_OPERATION_FK_2;
ALTER TABLE MAILBOX_OPERATION DROP CONSTRAINT MAILBOX_OPERATION_FK_1;
ALTER TABLE MAILBOX_OPERATION_CONFIG DROP CONSTRAINT MAILBOX_OPERATION_FK_2;

DROP TABLE MAILBOX;
DROP TABLE MAILBOX_ACCOUNT;
DROP TABLE MAILBOX_ACCOUNT_CONFIG;
DROP TABLE MAILBOX_CONFIG;
DROP TABLE MAILBOX_INFO;
DROP TABLE MAILBOX_MESSAGE;
DROP TABLE MAILBOX_MESSAGE_OPERATION;
DROP TABLE MAILBOX_OPERATION;
DROP TABLE MAILBOX_OPERATION_CONFIG;

CREATE TABLE MAILBOX(
   ID_MAILBOX varchar2(40) PRIMARY KEY NOT NULL,
   DESCRIPTION varchar2(250),
   NAME varchar2(45) NOT NULL UNIQUE,
   PROCESS_FLOW clob NOT NULL,
   STATUS varchar2(10) NOT NULL,
   FOLDER varchar2(50) NOT NULL,
   ID_ACCOUNT varchar2(40)
);

CREATE TABLE MAILBOX_ACCOUNT (
	ID_ACCOUNT varchar2(40) PRIMARY KEY NOT NULL,   
	ACCOUNT varchar2(100) NOT NULL UNIQUE
);

CREATE TABLE MAILBOX_ACCOUNT_CONFIG (
   CONFIG_KEY varchar2(40) NOT NULL,
   CONFIG_VALUE varchar2(400) NOT NULL,
   ID_ACCOUNT varchar2(40) NOT NULL,
   CONSTRAINT MAILBOX_ACCOUNT_CONFIG_PK PRIMARY KEY (ID_ACCOUNT,CONFIG_KEY)
);

CREATE TABLE MAILBOX_CONFIG (
   CONFIG_KEY varchar2(100),
   ID_MAILBOX varchar2(40) NOT NULL,
   CONFIG_VALUE varchar2(400) NOT NULL,
   CONSTRAINT MAILBOX_CONFIG_PK PRIMARY KEY (CONFIG_KEY,ID_MAILBOX)
);

CREATE TABLE MAILBOX_MESSAGE (
   MESSAGE_ID varchar2(400) NOT NULL,
   STATUS varchar2(30) NOT NULL,
   STATUS_MESSAGE varchar2(4000),
   URL_MIME varchar2(300),
   ID_MAILBOX varchar2(40) NOT NULL,
   DATAMAIL blob,
   DATE_DISCHARGED date not null,
   MESSAGE_UID NUMBER(15,0),
   MAILBOX_UID_VALIDITY NUMBER(15,0),
   CONSTRAINT MAILBOX_MESSAGE_PK PRIMARY KEY (MESSAGE_ID,ID_MAILBOX)
);

CREATE TABLE MAILBOX_MESSAGE_OPERATION
(
   ID_MAILBOXOPERATION varchar2(45) NOT NULL,
   MESSAGE_ID varchar2(400) NOT NULL,
   OPERATION_STATUS varchar2(30) NOT NULL,
   OPERATION_TRY_NUM number(3) NOT NULL,
   OPERATION_VALUE clob,
   OPERATION_VARIABLE_VALUE varchar2(500),
   ID_MAILBOX varchar2(400) NOT NULL,
   DATE_OPERATION date not null,
   CONSTRAINT MAILBOX_MESSAGE_OPERATION_PK PRIMARY KEY (ID_MAILBOXOPERATION,MESSAGE_ID,ID_MAILBOX)
);

CREATE TABLE MAILBOX_OPERATION (
   ID_MAILBOX_OPERATION varchar2(45) PRIMARY KEY NOT NULL,
   OPERATION_NAME varchar2(45) NOT NULL,
   ID_MAILBOX varchar2(40) NOT NULL
);

CREATE TABLE MAILBOX_OPERATION_CONFIG (
   CONFIG_KEY varchar2(100) NOT NULL,
   ID_MAILBOX_OPERATION varchar2(45) NOT NULL,
   CONFIG_VALUE varchar2(400) NOT NULL,
   CONSTRAINT MAILBOX_OPERATION_CONFIG_PK PRIMARY KEY (CONFIG_KEY,ID_MAILBOX_OPERATION)
);

CREATE TABLE MAILBOX_INFO (
   INFO_KEY VARCHAR2(100) NOT NULL, 
   ID_MAILBOX VARCHAR2(40) NOT NULL, 
   INFO_VALUE VARCHAR2(400), 
   CONSTRAINT MAILBOX_INFO_PK PRIMARY KEY (INFO_KEY, ID_MAILBOX)
); 

ALTER TABLE MAILBOX ADD (CONSTRAINT MAILBOX_FK FOREIGN KEY (ID_ACCOUNT) REFERENCES MAILBOX_ACCOUNT (ID_ACCOUNT));
ALTER TABLE MAILBOX_ACCOUNT_CONFIG ADD (CONSTRAINT MAILBOX_ACCOUNT_CONFIG_FK FOREIGN KEY (ID_ACCOUNT) REFERENCES MAILBOX_ACCOUNT (ID_ACCOUNT));
ALTER TABLE MAILBOX_CONFIG ADD (CONSTRAINT MAILBOX_CONFIG_FK FOREIGN KEY (ID_MAILBOX) REFERENCES MAILBOX (ID_MAILBOX));
ALTER TABLE MAILBOX_INFO ADD (CONSTRAINT MAILBOX_INFO_FK FOREIGN KEY (ID_MAILBOX) REFERENCES MAILBOX (ID_MAILBOX));
ALTER TABLE MAILBOX_MESSAGE ADD (CONSTRAINT MAILBOX_MESSAGE_FK FOREIGN KEY (ID_MAILBOX) REFERENCES MAILBOX (ID_MAILBOX));
ALTER TABLE MAILBOX_MESSAGE_OPERATION ADD (CONSTRAINT MAILBOX_MESSAGE_OPERATION_FK_1 FOREIGN KEY (ID_MAILBOXOPERATION) REFERENCES MAILBOX_OPERATION (ID_MAILBOX_OPERATION ));
ALTER TABLE MAILBOX_MESSAGE_OPERATION ADD (CONSTRAINT MAILBOX_MESSAGE_OPERATION_FK_2 FOREIGN KEY (MESSAGE_ID, ID_MAILBOX) REFERENCES MAILBOX_MESSAGE (MESSAGE_ID, ID_MAILBOX));
ALTER TABLE MAILBOX_OPERATION ADD (CONSTRAINT MAILBOX_OPERATION_FK_1 FOREIGN KEY ( ID_MAILBOX ) REFERENCES MAILBOX ( ID_MAILBOX ));
ALTER TABLE MAILBOX_OPERATION_CONFIG ADD (CONSTRAINT MAILBOX_OPERATION_FK_2 FOREIGN KEY (ID_MAILBOX_OPERATION)REFERENCES MAILBOX_OPERATION (ID_MAILBOX_OPERATION));