SET DEFINE OFF;

Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('3', 'Tagged Image File', NULL, NULL, 'tiff', 
    NULL, '--', '3', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.938000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.938000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/tiff');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('4', 'Joint Photographic Experts Group', NULL, NULL, 'jpg', 
    NULL, '--', '4', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.939000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.939000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/jpeg');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('5', 'Microsoft Excel', NULL, NULL, 'xls', 
    NULL, '--', '5', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.940000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.940000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/excel');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('6', 'Ascii', NULL, NULL, 'txt', 
    NULL, '--', '6', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.942000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.942000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'text/plain');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('7', 'Lotus Word Pro', NULL, NULL, 'lwp', 
    NULL, '--', '7', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.944000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.944000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/vnd.lotus-wordpro');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('8', 'Lotus 1-2-3', NULL, NULL, 'wk1', 
    NULL, '--', '8', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.945000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.945000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/x-123');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('9', 'Rich Text Format', NULL, NULL, 'rtf', 
    NULL, '--', '9', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.945000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.945000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'text/richtext');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('10', 'Archivio compresso (zip, gzip, gz, tgz)', NULL, NULL, 'zip', 
    NULL, '--', '10', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.947000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.947000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/x-compressed');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('11', 'AutoCAD DWG', NULL, NULL, 'dwg', 
    NULL, '--', '11', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.949000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.949000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/acad');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('12', 'Design Web Format', NULL, NULL, 'dwf', 
    NULL, '--', '12', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.949000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.949000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'model/vnd.dwf');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('13', 'Tape archive (TAR)', NULL, NULL, 'tar', 
    NULL, '--', '13', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.950000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.950000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/x-tar');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('14', 'Drawing Exchange Format', NULL, NULL, 'dxf', 
    NULL, '--', '14', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.951000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.951000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/dxf');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('15', 'Microsoft Power Point', NULL, NULL, 'ppt', 
    NULL, '--', '15', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.952000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.952000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/powerpoint');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('16', 'Portable Network Graphics', NULL, NULL, 'png', 
    NULL, '--', '16', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.952000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.952000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/png');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('17', 'File bitmap', NULL, NULL, 'bmp', 
    NULL, '--', '17', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.953000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.953000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/bmp');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('18', 'Rhosal Archive (RAR)', NULL, NULL, 'rar', 
    NULL, '--', '18', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.955000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.955000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/x-rar-compressed');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('19', 'Graphics Interchange Format (GIF)', NULL, NULL, 'gif', 
    NULL, '--', '19', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.956000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.956000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/gif');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('20', 'Icon', NULL, NULL, 'ico', 
    NULL, '--', '20', 'binary', NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.957000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.957000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'image/x-icon');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('21', 'Microsoft Project', NULL, NULL, 'mpp', 
    NULL, '--', '21', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 0, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.958000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.958000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/vnd.ms-project');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('22', 'OpenDocument Text Document', NULL, NULL, 'odt', 
    NULL, '--', '22', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.960000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.960000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/vnd.oasis.opendocument.text');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('23', 'OpenDocument Spreadsheet', NULL, NULL, 'ods', 
    NULL, '--', '23', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.961000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.961000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/vnd.oasis.opendocument.spreadsheet');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('24', 'OpenDocument Presentation', NULL, NULL, 'odp', 
    NULL, '--', '24', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.962000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.962000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/vnd.oasis.opendocument.presentation');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('25', 'eXtensible Markup Language', NULL, NULL, 'xml', 
    NULL, '--', '25', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:51:59', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.51.59.261000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.51.59.261000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/xml');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('26', 'HyperText Markup Language', NULL, NULL, 'html', 
    NULL, '--', '26', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:51:59', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.51.59.265000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.51.59.265000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'text/html');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('1', 'Microsoft Word', NULL, NULL, 'doc', 
    NULL, '--', '1', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.885000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.885000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/msword');
Insert into T_ANAG_FORMATI_DIG
   (ID_DIG_FORMAT, NOME, VERSIONE, ALTRI_NOMI, ESTENSIONE_PRINCIPALE, 
    DES_ESTESA, ID_REC_DIZ_REGISTRO_FMT, ID_IN_REGISTRO_FMT, ID_REC_DIZ_TIPO_FMT, BYTE_ORDERS, 
    DT_RILASCIO, DT_DESUPP, RISCHI, SVILUPPATO_DA, MANTENUTO_DA, 
    FLG_COPYRIGHT, FLG_INDICIZZABILE, FLG_STATO, TS_AGG_STATO, TS_INS, 
    ID_UTE_INS, TS_ULTIMO_AGG, ID_UTE_ULTIMO_AGG, FLG_ANN, MIMETYPE_PRINCIPALE)
 Values
   ('2', 'Portable Document Format', NULL, NULL, 'pdf', 
    NULL, '--', '2', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    0, 1, 'A', TO_DATE('05/31/2013 23:31:42', 'MM/DD/YYYY HH24:MI:SS'), TO_TIMESTAMP('31/05/2013 23.31.42.937000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), 
    NULL, TO_TIMESTAMP('31/05/2013 23.31.42.937000','DD/MM/YYYY fmHH24fm.MI.SS.FF'), NULL, 0, 'application/pdf');

COMMIT;
/	 

SHOW ERRORS;

SET DEFINE ON;